server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: nanos:8848 
    gateway:
      globalcors: 
        add-to-simple-url-handler-mapping: true 
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
            allowedMethods: 
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" 
            allowCredentials: true 
            maxAge: 360000 
      routes:
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/user/**
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**

